/**
 * Lucide React icon mapping.
 * Use Lucide for standard UI icons (settings, chevron, filter, bell, alert…).
 * Use custom icons for brand / Discord-specific / hand-drawn SVGs.
 *
 * Tree-shaking: only imported icons are bundled by Vite.
 */
import {
  Search,
  X,
  Plus,
  Trash2,
  RefreshCw,
  ChevronDown,
  ChevronUp,
  ChevronRight,
  ChevronLeft,
  Settings,
  Filter,
  Bell,
  AlertTriangle,
  AlertCircle,
  Info,
  Check,
  CheckCircle,
  Copy,
  Download,
  ExternalLink,
  Eye,
  EyeOff,
  Calendar,
  Clock,
  ArrowUpDown,
  MessageSquare,
  Reply,
  Hash,
  Users,
  User,
  BarChart3,
  Activity,
  Zap,
  Database,
  Shield,
  Globe,
  Link2,
  MoreHorizontal,
  Loader2,
  type LucideIcon,
} from "lucide-react";

export const LUCIDE_MAP = {
  search: Search,
  x: X,
  plus: Plus,
  trash: Trash2,
  refresh: RefreshCw,
  "chevron-down": ChevronDown,
  "chevron-up": ChevronUp,
  "chevron-right": ChevronRight,
  "chevron-left": ChevronLeft,
  settings: Settings,
  filter: Filter,
  bell: Bell,
  "alert-triangle": AlertTriangle,
  "alert-circle": AlertCircle,
  info: Info,
  check: Check,
  "check-circle": CheckCircle,
  copy: Copy,
  download: Download,
  "external-link": ExternalLink,
  eye: Eye,
  "eye-off": EyeOff,
  calendar: Calendar,
  "clock-lucide": Clock,
  "arrow-up-down": ArrowUpDown,
  "message-square": MessageSquare,
  reply: Reply,
  "hash-lucide": Hash,
  "users-lucide": Users,
  "user-lucide": User,
  "bar-chart": BarChart3,
  activity: Activity,
  zap: Zap,
  database: Database,
  shield: Shield,
  globe: Globe,
  link: Link2,
  "more-horizontal": MoreHorizontal,
  loader: Loader2,
} as const satisfies Record<string, LucideIcon>;

export type LucideIconName = keyof typeof LUCIDE_MAP;
